defaultSpace: personal
home: /Users/alexis/dev
spaces:
    - personal
    - unifox
    - advent-of-code
    - epitech
templates:
    cargo-new:
        commands:
            - cargo new PATH
        frominside: false
