format = """
$directory$jobs\
$git_branch$git_state$git_status\
$python$nodejs
$character
"""

[directory]
style = "#87DFEB"

[jobs]
format = "[$symbol$number]($style) "
symbol = "🚀"
number_threshold = 1
style = ""

[git_branch]
format = "\\([$branch]($style)"
style = "#E0BCFF"

[git_status]
format = """
[$ahead_behind$stashed( \
[$staged$modified$untracked](#F48FB1))](#FFE6B3)\\) """

diverged = "$ahead$behind"
ahead = "↑$count"
behind = "↓$count"

stashed = "≡$count"
staged = "+$count"
untracked = "…$count"
modified = "~$count"

[python]
symbol = "\\[py\\] "
style = "#8A889D"

[nodejs]
symbol = "\\[js\\] "
style = "#8A889D"

[character]
success_symbol = "❯"
error_symbol = "[❯](#F48FB1)"
# ❯ or ➜
