format = """
$directory$jobs\
$git_branch$git_state$git_status\
$python$nodejs
$character
"""

[directory]
style = "#87DFEB"

[jobs]
format = "[$symbol]($style)$number "
symbol = "*"
number_threshold = 1
style = ""

[git_branch]
style = "#E0BCFF"

[git_status]
diverged = "$ahead$behind"
ahead = "↑$count"
behind = "↓$count"

stashed = "≡$count"
staged = "+$count"
untracked = "…$count"
modified = "~$count"

deleted = ""
renamed = ""

[python]
symbol = "python "
style = "#8A889D"

[nodejs]
symbol = "javascript "
style = "#8A889D"

[character]
success_symbol = "❯"
error_symbol = "[❯](#F48FB1)"
# ❯ or ➜
