format = """
$directory\
$git_branch$git_state$git_status\
$python$nodejs
$character
"""

right_format = """
$jobs
"""

[directory]
style = "cyan"

[jobs]
format = "[$symbol]($style)$number "
symbol = "*"
number_threshold = 1
style = ""

[git_branch]
style = "purple"

[git_status]
style = "red"

diverged = "$ahead$behind"
ahead = "↑$count"
behind = "↓$count"

stashed = "≡$count"
staged = "+$count"
untracked = "…$count"
modified = "~$count"

deleted = ""
renamed = ""

[python]
symbol = "python "
style = "#8A889D"

[nodejs]
symbol = "javascript "
detect_extensions = []
style = "#8A889D"

[character]
success_symbol = "❯"
error_symbol = "[❯](red)"
# ❯ or ➜
