format = """
$directory\
$git_branch$git_state$git_status\
$python$nodejs$lua$php\
$character
"""

right_format = """
$jobs
"""

[directory]
style = "cyan"

[jobs]
format = "[$symbol$number]($style) "
number_threshold = 1
symbol = "*"
style = "bold yellow"

[git_branch]
only_attached = true
style = "purple"

[git_status]
style = "red"

diverged = "$ahead$behind"
ahead = "↑$count"
behind = "↓$count"

stashed = "≡$count"
staged = "+$count"
untracked = "…$count"
modified = "~$count"

deleted = "-$count"
renamed = "$count"

[python]
symbol = "python "
# style = "#8A889D"

[nodejs]
detect_extensions = []

[lua]
symbol = "lua "
style = "bold black"

[character]
# ❯ or ➜
success_symbol = "[❯](white)"
