format = """
$directory\
$git_branch$git_state$git_status\
$python\
$ocaml\
$character
"""

right_format = """
$jobs\
"""

[directory]
read_only = '(r)'
read_only_style = 'green'
style = "cyan"

[jobs]
format = "[$symbol$number]($style) "
number_threshold = 1
symbol = "*"
style = "bold purple"

[git_branch]
format = "@[$branch]($style) "
style = "purple"

[git_status]
style = "red"
# format = '[($conflicted )($stashed )($deleted )($renamed )($modified )($staged )($untracked )]($style)'

diverged = "$ahead$behind"
ahead = "↑$count"
behind = "↓$count"

stashed = "≡$count"
staged = "+$count"
untracked = "…$count"
modified = "~$count"

deleted = "-$count"
renamed = "*$count"

[python]
format = '#[(($virtualenv-)$version )]($style)'
style = "green"

[nodejs]
symbol = ""

[golang]
symbol = "go "
style = "italic bold black"

[elixir]
symbol = "elixir "
style = "italic bold black"

[ocaml]
format = '$switch_indicator[$switch_name-$version ]($style)'
global_switch_indicator = '#'
style = "green"


[character]
# ❯ or ➜
success_symbol = "[➜](white)"
error_symbol = "[➜](red)"

vimcmd_symbol = "[N](green)"
vimcmd_visual_symbol = "[V](purple)"

[shell]
disabled = false

[shlvl]
disabled = false
style = "#6e738d"
format = '[\($shlvl\) ]($style)'
repeat = true
threshold = 2
repeat_offset = 1
