format = """
$directory\
$git_branch$git_state$git_status\
$python$nodejs$lua$golang$elixir\
$character
"""

right_format = """
$jobs
"""

[directory]
read_only = '(r)'
read_only_style = 'green'
style = "cyan"

[jobs]
format = "[$symbol$number]($style) "
number_threshold = 1
symbol = "*"
style = "bold yellow"

[git_branch]
style = "purple"

[git_status]
style = "red"

diverged = "$ahead$behind"
ahead = "↑$count"
behind = "↓$count"

stashed = "≡$count"
staged = "+$count"
untracked = "…$count"
modified = "~$count"

deleted = "-$count"
renamed = "*$count"

[python]
symbol = "python "
style = "italic bold black"

[nodejs]
detect_extensions = []
symbol = "node "
style = "italic bold black"

[lua]
symbol = "lua "
style = "italic bold black"

[golang]
symbol = "go "
style = "italic bold black"

[elixir]
symbol = "elixir "
style = "italic bold black"

[character]
# ❯ or ➜
success_symbol = "[➜](white)"
error_symbol = "[➜](red)"

vimcmd_symbol = "[N](green)"
vimcmd_visual_symbol = "[V](purple)"
